services:
  - type: web
    name: django-app
    env: python
    pythonVersion: "3.12.6"
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn labourer_admin.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
